name: Deploy Migrations

on:
  push:
    branches:
      - staging
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Debug secrets
        run: |
          echo "SUPABASE_PROJECT_ID length: ${#SUPABASE_PROJECT_ID}"
          echo "SUPABASE_ACCESS_TOKEN length: ${#SUPABASE_ACCESS_TOKEN}"
          echo "SUPABASE_DB_PASSWORD length: ${#SUPABASE_DB_PASSWORD}"
          echo "Project ID (masked): ${SUPABASE_PROJECT_ID:0:4}...${SUPABASE_PROJECT_ID: -4}"

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID --debug
      - run: supabase db push --include-all
